title: Sandmann, H.
logo: https://avatars3.githubusercontent.com/u/20843348
description: São Paulo, 22 April 2015<br/><small><a href="https://goo.gl/maps/7nASYbXJuz62">Cine Café Fellini</a></small>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal