site_name: Humberto Sandmann
repo_url: https://github.com/hsandmann/hsandmann.github.com
repo_name: hsandmann.github.com

theme:
  name: material
  custom_dir: overrides
  palette:
    # primary: grey
    # Light mode
    - scheme: default
      primary: grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - scheme: slate
      primary: grey
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
  features:
    # - announce.dismiss
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips
    - header.autohide
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.path
    - navigation.tracking
  favicon: assets/img/favicon.svg
  logo: assets/img/logo.svg
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      # quote: fontawesome/solid/quote-left
      quote: fontawesome/solid/book
    repo: fontawesome/brands/git-alt

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      title: Humberto Sandmann

plugins:
  - glightbox
  - minify:
      minify_html: true
  - page-to-pdf:
      format: Letter

extra_css:
  - stylesheets/extra.css
