site_name: Humberto Sandmann
repo_url: https://github.com/hsandmann/hsandmann.github.com
repo_name: hsandmann.github.com

theme:
  name: material
  palette:
    # primary: grey
    # Light mode
    - scheme: default
      primary: grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - scheme: slate
      primary: grey
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
  features:
    # - announce.dismiss
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips
    - header.autohide
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.path
    - navigation.tracking
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      # quote: fontawesome/solid/quote-left
      quote: fontawesome/solid/book
    repo: fontawesome/brands/git-alt

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true  
  - footnotes
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - toc:
      title: Humberto Sandmann

plugins:
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors
  - git-committers:
      repository: hsandmann/hsandmann.github.com
      branch: main
  - search
  - badges
  - markdown-exec
  - render_swagger:
      allow_arbitrary_locations : true
  - termynal:
      prompt_literal_start:
        - "$"
        - ">"

extra_javascript:
  # - javascripts/extra.js
  - https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
  # - https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css
